name: My first workflow


on: [push, fork]


jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Welcome message
              run: |
                echo "Hello, world!"
                echo "This is my first workflow."
                ls -a
                cat README.md