name: My first workflow


on: [push, fork]


jobs: 
    first_job:
        runs-on: self-hosted
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Welcome message
              run: |
                echo "Hello, world!"
                echo "This is my first workflow."
                ls -a
                cat README.md

            - name: Generate ASCII content
              run: cowsay -f dragon "Run for cover" >> dragon.txt
