name: Generate ASCII

on: [push, pull_request]

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install cowsay
              run: sudo apt-get install cowsay -y

            - name: Execute cowsay cmd
              run: cowsay -f dragon "Run for cover" >> dragon.txt

            - name: Test if file exists
              run: grep -i "cover" dragon.txt

            - name: Read file content
              run: cat dragon.txt

            - name: List files
              run: ls -a
            

            - name: Generate ASCII content
              run: cowsay -f dragon "Run for cover" >> dragon.txt