name: Generate ASCII

on: [push, pull_request]

jobs: 
    ascii_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Execting shellscript
              run: |
               chmod +x script.sh
               ./script.sh

            - name: Generate ASCII content
              run: cowsay -f dragon "Run for cover" >> dragon.txt
